### ISSUE TITLE
Error in last line

### ISSUE THREAD

**Issue by nullblackvoid** [defparam/h1passets#10]
Hi,

Latest version. 

While running  `python3 h1passets token url`
Getting this error:
```
Traceback (most recent call last):
  File "h1passets", line 118, in <module>
    graphql_token = get_h1_graphql_token(host_session_token)
  File "h1passets", line 51, in get_h1_graphql_token
    jsn = json.loads(resp.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Wondering I'm the only one who's having this error.

Thanks

**Comment by thaivd98** [comment]
I got the same issue

**Comment by nullblackvoid** [comment]
@thaivd98  I found another tool: https://github.com/sw33tLie/bbscope
Works fine.
